language: java

jdk:
  - oraclejdk8

after_success:
  - if [ -e ./gradlew ]; then ./gradlew docBundle jacocoTestReport;else gradle docBundle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)
